---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: etcd-browser
  namespace: datamesh
spec:
  replicas: 1
  template:
    metadata:
      namespace: datamesh
    spec:
      containers:
      - name: etcd-browser
        image: lmarsden/etcd-browser:latest
        ports:
        - containerPort: 8000
