stages:
    - clean

before_script:
    - mkdir -p gopath
    - export GOPATH=$(pwd)/gopath
    - cd gopath
    - mkdir -p src/github.com/lukemarsden
    - ln -s `realpath ..` ./src/github.com/lukemarsden/datamesh
    - cd src/github.com/lukemarsden/datamesh

clean:
    stage: clean
    script:
        - pwd
        - cd frontend
        - ls -la
        - sudo ls -la
        - cat cd /var/opt/gitlab/gitlab-rails/shared/artifacts

