stages:
    - sync
    - build
    - merge
    - test
    - deploy

sync_github:
    # push all commits to all branches to github for safe keeping
    stage: sync
    script:
        - git log
        - git remote rm github || true
        - git remote add github git@github.com:datamesh-io/datamesh
        - git checkout -b $CI_BUILD_REF_NAME || true
        - pwd
        - git remote -v
        - git push --force github $CI_BUILD_REF_NAME

before_script:
    - mkdir -p gopath
    - export GOPATH=$(pwd)/gopath
    - cd gopath
    - mkdir -p src/github.com/datamesh-io
    - ln -s `realpath ..` ./src/github.com/datamesh-io/datamesh
    - cd src/github.com/datamesh-io/datamesh

build_client_linux:
    stage: build
    tags:
        - ubuntu-16.10
        - fast
    script:
        - cd cmd/dm/
        - ./rebuild.sh Linux
    artifacts:
        paths:
            - binaries
        expire_in: 1 week

build_client_macos:
    stage: build
    tags:
        - ubuntu-16.10
        - fast
    script:
        - cd cmd/dm/
        - ./rebuild.sh Darwin
    artifacts:
        paths:
            - binaries
        expire_in: 1 week

build_server:
    stage: build
    tags:
        - ubuntu-16.10
        - fast
    script:
        - cd cmd/datamesh-server
        - ./rebuild.sh
    artifacts:
        paths:
            - cmd/datamesh-server/target
        expire_in: 1 week

build_frontend:
    stage: build
    tags:
        - ubuntu-16.10
        - fast
    script:
        - cd frontend
        - ./rebuild.sh
    artifacts:
        paths:
            - frontend/dist.tar.gz

build_frontend_test_runner:
    stage: build
    tags:
        - ubuntu-16.10
        - fast
    script:
        - cd frontend
        - ./rebuild_test_runner.sh

# we have already built the binaries and frontend code
# let's produce a final production image of the inner server
# that has the frontend files burnt
# it will overwrite $(hostname).local:80/datamesh/datamesh-server:latest
# so the tests use the image with the frontend
merge_frontend:
    stage: merge
    tags:
        - ubuntu-16.10
        - fast
    script:
        - cd frontend
        - ls -la
        - gzip -dc dist.tar.gz | tar -xof -
        - cd ..
        - mv frontend/dist cmd/datamesh-server/dist
        - cd cmd/datamesh-server
        - ./mergebuild.sh

# run sanity check that things still work on Windows and macOS
windows_docker_stable:
    stage: test
    tags:
        - windows
        - docker-stable
    script:
        - | bash -c "
            cd cmd/datamesh-server;
            docker build -t datamesh-server . || (sleep 30; docker build -t datamesh-server .)
            cd ../..
            ./smoke.sh $(pwd)/binaries/Linux/dm datamesh-server
            docker system prune -fa
            "

macos_docker_stable:
    stage: test
    tags:
        - macos
        - docker-stable
    script:
        - cd cmd/datamesh-server
        # Possible to build just the "prod" image because binaries got passed
        # as artifact in cmd/datamesh-server/target
        - docker build -t datamesh-server . || (sleep 30; docker build -t datamesh-server .)
        - cd ../..
        - ./smoke.sh $(pwd)/binaries/Darwin/dm datamesh-server
        - docker system prune -fa

macos_docker_edge:
    stage: test
    tags:
        - macos
        - docker-edge
    script:
        - cd cmd/datamesh-server
        # Possible to build just the "prod" image because binaries got passed
        # as artifact in cmd/datamesh-server/target
        - docker build -t datamesh-server . || (sleep 30; docker build -t datamesh-server .)
        - cd ../..
        - ./smoke.sh $(pwd)/binaries/Darwin/dm datamesh-server
        - docker system prune -fa

# run full dind tests on linux
linux_single_node:
    stage: test
    tags:
        - ubuntu-16.10
        - fast
    script:
        - ./test.sh -run TestSingleNode

linux_two_nodes_same_cluster:
    stage: test
    tags:
        - ubuntu-16.10
        - fast
    script:
        - ./test.sh -run TestTwoNodesSameCluster

linux_two_single_node_clusters:
    stage: test
    tags:
        - ubuntu-16.10
        - fast
    script:
        - ./test.sh -run TestTwoSingleNodeClusters

linux_three_single_node_clusters:
    stage: test
    tags:
        - ubuntu-16.10
        - fast
    script:
        - ./test.sh -run TestThreeSingleNodeClusters

deploy_client_binaries:
    stage: deploy
    tags:
        - ubuntu-16.10
        - fast
    script:
        - rsync -avz binaries/{Linux,Darwin} luke@neo.lukemarsden.net:/pool/releases/
    only:
        - master

deploy_server_docker_image:
    stage: deploy
    tags:
        - ubuntu-16.10
        - fast
    script:
        - docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
        - docker tag $(hostname).local:80/datamesh/datamesh-server:latest quay.io/datamesh/datamesh-server:latest
        - docker push quay.io/datamesh/datamesh-server:latest
    only:
        - master

frontend:
    stage: test
    tags:
        - ubuntu-16.10
        - fast
    script:
        - mkdir frontend_artifacts
        - ./test.sh -run TestFrontend
    after_script:
        - tar -xf frontend_artifacts.tar -C frontend_artifacts
        - sudo rm frontend_artifacts.tar
        - ls -la frontend_artifacts
    artifacts:
        paths:
            - frontend_artifacts

