version: '2'
services:
  router:
    image: binocarlos/noxy
    container_name: datamesh_router
    ports:
      - "80:80"
    depends_on:
      - frontend
      - api
    links:
      - frontend:frontend
      - api:api
    environment:
      NOXY_API_FRONT: /rpc
      NOXY_API_HOST: api
      NOXY_DEFAULT_HOST: frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: datamesh_frontend
    environment:
      - MANUALRUN
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules/
    entrypoint:
      - "bash"
      - "run.sh"