version: '2'
services:
  router:
    image: binocarlos/noxy
    container_name: datamesh_router
    ports:
      - "80:80"
    depends_on:
      - frontend
      - api
    net: host
    environment:
      NOXY_API_FRONT: /rpc
      NOXY_API_HOST: localhost:6969
      NOXY_DEFAULT_HOST: localhost:8080
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: datamesh_frontend
    ports:
      - "8080:80"
    environment:
      - MANUALRUN
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules/
    entrypoint:
      - "bash"
      - "run.sh"