# Build with:
FROM ubuntu:yakkety
ENV SECURITY_UPDATES 2017-01-19
RUN apt-get -y update && apt-get -y install curl golang-1.7 git
ENV PATH=$PATH:/go/bin:/usr/lib/go-1.7/bin
ENV GOPATH=/go
RUN go get github.com/tools/godep
RUN mkdir /target
ADD . /go/src/github.com/lukemarsden/datamesh/cmd/dm
WORKDIR /go/src/github.com/lukemarsden/datamesh/cmd/dm
#GOPATH=/go GOOS=Darwin PATH=$PATH:/usr/lib/go-1.7/bin go build -o /target/dm
