---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: datamesh-provisioner
      labels:
        name: datamesh-provisioner
      namespace: datamesh
  - apiVersion: rbac.authorization.k8s.io/v1alpha1
    kind: ClusterRole
    metadata:
      name: datamesh-provisioner-runner
    rules:
      - apiGroups: [""]
        resources: ["persistentvolumes"]
        verbs: ["get", "list", "watch", "create", "delete"]
      - apiGroups: [""]
        resources: ["persistentvolumeclaims"]
        verbs: ["get", "list", "watch", "update"]
      - apiGroups: ["storage.k8s.io"]
        resources: ["storageclasses"]
        verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["list", "watch", "create", "update", "patch"]
  - apiVersion: rbac.authorization.k8s.io/v1alpha1
    kind: ClusterRoleBinding
    metadata:
      name: datamesh-provisioner
    subjects:
      - kind: ServiceAccount
        name: datamesh-provisioner
        namespace: datamesh
    roleRef:
      kind: ClusterRole
      name: datamesh-provisioner-runner
      apiGroup: rbac.authorization.k8s.io
  - apiVersion: apps/v1beta1 # for versions <1.8.0; use apps/v1beta2 for versions >=1.8.0
    kind: Deployment
    metadata:
      name: datamesh-dynamic-provisioner
      namespace: datamesh
      labels:
        app: datamesh-dynamic-provisioner
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: datamesh-dynamic-provisioner
      template:
        metadata:
          labels:
            app: datamesh-dynamic-provisioner
        spec:
          serviceAccount: datamesh-provisioner
          containers:
          - name: datamesh-dynamic-provisioner
            image: 'quay.io/datamesh/datamesh-dynamic-provisioner:latest'
            imagePullPolicy: "IfNotPresent"
            env:
            - name: DATAMESH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: datamesh
                  key: datamesh-admin-password.txt
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: datamesh
    provisioner: datamesh/datamesh-dynamic-provisioner
    parameters:
      datameshNode: "datamesh"
