---
# from https://github.com/coreos/etcd-operator/blob/master/doc/user/rbac.md
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: example-etcd-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # "cluster-admin" works for kubeadm clusters; "admin" apparently works for
  # Tectonic. You may need to update this to match with your cluster's
  # clusterrole config.
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: datamesh
